spring.application.name=R2S_LeadOps
spring.datasource.url=jdbc:postgresql://localhost:5432/r2s_leadops
spring.datasource.username=postgres
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=R2SLeadOps_JWT_SecretKey_2026_This_Is_More_Than_32_Bytes!
app.jwt.expiration-ms=86400000